<div class='dx-viewport demo-container' width='90%'>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br>

    <table style="width:90%">
        <tr>
            <td width="33%" style="text-align: center">
                <div id="gauge1"></div>
            </td>
            <td width="33%" style="text-align: center">
                <div id="gauge2"></div>
            </td>
            <td width="33%" style="text-align: center">
                <div id="gauge3"></div>
            </td>
        </tr>

        <tr>
            <td colspan="3">
                <br><br><br><br><br><br>
                <div id='chart' width='90%'></div>
            </td>
        </tr>

        <tr style="background-color: white">
            <td colspan="3" style="background-color: white">
                <br><br><br><br><br><br>
                <div id="chart_line"></div>
            </td>
        </tr>
    </table>

</div>



<!-- <br><br>
    <div id='chart-demo' width='90%'>
<br><br>
        <div id='chart' width='90%'></div>
<br><br><br><br>
        <div id="chart_line"></div>

        <!-- <div class="options">
            <div class="caption">Options</div>
            <div class="option">
                <span>Series Type</span>
                <div id="types"></div>
            </div>
        </div> -->

</div>
</div> -->